### ISSUE TITLE
Turn TUF/TL comparison into blog post

### ISSUE THREAD

**Issue by brainwane** [secure-systems-lab/ssl-site#92]
@mnm678 this is a request to turn ["Compromise detection vs resilience: contrasting Transparent Logs and The Update Framework"](https://docs.google.com/document/d/1gyy7sdR6RZtIWwrlKHVSJOvO0cnKTDMcgOPl6yDgmgM/edit?usp=sharing) into an lab blog post (a new file in `_posts/`), ideally this weekend. :-)

(And then to publicize it [on the TUF mailing list](https://groups.google.com/d/msg/theupdateframework/DF0tp691W5s/FSP9_DKwEAAJ), in [the TUF roadmap issue](https://github.com/pypa/warehouse/issues/5247), and [in the PEP 458 Discourse thread](https://discuss.python.org/t/pep-458-surviving-a-compromise-of-pypi/2648).)

(And in case you think "argh, redoing the formatting", let me introduce you to the joys of `pandoc`!)

**Comment by brainwane** [comment]
@mnm678 will you be able to do this in the next few days?

**Comment by jhdalek55** [comment]
I looked at it over the weekend and I believe Marina was going to pass it to Justin to review. Justin generally reviews these posts before we send them out.

Lois

**Comment by JustinCappos** [comment]
@Marina Moore <mnm678@gmail.com>  Was this forwarded to me?

**Comment by mnm678** [comment]
@JustinCappos Yes, but I'll resend it

**Comment by brainwane** [comment]
I believe Trishank is now working on this - not sure.

**Comment by jhdalek55** [comment]
As of Friday night, when I checked in with Trishank via Slack, he hadn't been able to get to it. So I said I would get it done either over the weekend or by Monday.

I was planning to work on this tonight. Trishank if you are working on doing so, be my guest.

Lois

**Comment by trishankatdatadog** [comment]
Case closed!

**Comment by brainwane** [comment]
https://ssl.engineering.nyu.edu/blog/2020-02-03-transparent-logs is up. Thanks.
